### ISSUE TITLE
C and C++ API:s

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1326]
More details in:
* ~https://github.com/rerun-io/rerun/issues/2516~
* #2919

We will eventually build a low-level C API for embedded platforms, but the above issues is about C++ in particular.

**Comment by asuper0** [comment]
How is this going on? I'd like to write C API which is wrapper of RUST API, and cover all the primitives. Expect your advise.

**Comment by crownedone** [comment]
It looks like they are still working on additional primitives (i.e #1630) and mentioned that they think about changing the structure of these in a way that makes interfacing with other languages easier.

That means writing a C interface now could be made obsolete/changed soon (please correct me).

Is there any more specific information on this? (Eagerly waiting to be able to use Rerun from C++!!!)

Wonder if you considered the use of some general data interface (like Protobuf)?

I'd be willing to contribute as well ;)

**Comment by Wumpf** [comment]
@asuper0 @crownedone We're making some good progress on generating Rust & Python APIs from data definition files since we figured by now that adding new components _and_ new language front ends is way too tedious otherwise. I sadly still can't give any timelines, but this gets us a _huge_ step towards supporting more languages and a C interface is going to be the first one added.

I deeply appreciate the willingness to help 🙇 , but given that we commited to that way now, anything landing regarding C is pretty much blocked by the codegen effort.
(There's plenty of other places where we could use help though, check the [Good First Issue](https://github.com/rerun-io/rerun/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and the [Quick Issue](https://github.com/rerun-io/rerun/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%8F%8E%EF%B8%8F+Quick+Issue%22) tags 😃 )

That said, if you want to pipe through something to C the easiest way right now is to write a Rust library depending on the Rerun crate that exposes what you need to C.

If you want to track the progress / are curious what the upcoming codegen things looks like check [PRs](https://github.com/rerun-io/rerun/pulls?q=is%3Apr+label%3Acodegen%2Fidl+) and [Issues](https://github.com/rerun-io/rerun/issues?q=is%3Aissuelabel%3Acodegen%2Fidl+) tagged with `codegen`

**Comment by asuper0** [comment]
> (There's plenty of other places where we could use help though, check the [Good First Issue](https://github.com/rerun-io/rerun/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and the [Quick Issue](https://github.com/rerun-io/rerun/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%8F%8E%EF%B8%8F+Quick+Issue%22) tags 😃 )
These issue may be too complicated for me🤣 I don't intend to go into the inner code.

My planning is writing a Rust proxy, which offers C-like API that receive raw data and convert them to rerun primitive datatype. 

While I had a experience of upgrading my code dependency of Rerun from 0.4.0 -> 0.5.1 -> 0.6.0, it could be promised that the Rust  proxy code will only have littte change with Rerun upgrading, and have no need to change the C API.

I think these work would't be too much.

**Comment by Wumpf** [comment]
New tracking issue for first version of C++ SDK that is posed to be available in 0.9.0:
* #2919
Keeping this open since it's the "original" and a bunch of people might monitor this

**Comment by emilk** [comment]
We now have a C++ API!
