### ISSUE TITLE
No outline when hovering rectangle in 2D view with selected image.

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#1597]
![hover_object_on_selected_image](https://user-images.githubusercontent.com/2624717/225364488-ff979c1b-3dce-4a71-aaec-9ed078d549b4.gif)

In a 2D view with both an image and rectangles, hovering over a rectangle doesn't show it's outline if the image is selected.

How to reproduce:

1. Run `./examples/python/tracking_hf_opencv/main.py`
2. Click on the image in the "rgb" space
3. Hover over a rectangle

**Comment by Wumpf** [comment]
Failing to reproduce this issue on main and on `andreas/outlines-tweaks`.

A confusing thing that I can repro (especially visible on `andreas/outlines-tweaks`) is that when one selects a rect and then hovers on the image itself the outline of the rectangle turns grey/hover-colored. This happens because there is is a different hover-mask value where the rectangle is (i.e. "not hovered") therefore there is a border line, therefore we draw a hover outline around the rectangle now.
Since (especially on `andreas/outline-tweaks`) hover outlines draw over selection outlines, what is left to see is the hover outline both around the image and all "internal cutouts", i.e. the rectangle in this case.
We could change what overdraws what, making selection outlines hide hover outlines, but for the general case this seems better.
