### ISSUE TITLE
Make GpuTexture2DHandle never-null

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1864]
Currently, `GpuTexture2DHandle` is defined as:

```
pub struct GpuTexture2DHandle(Option<GpuTexture>);

impl GpuTexture2DHandle {
    pub fn invalid() -> Self {
        Self(None)
    }
}
```

`GpuTexture2DHandle::invalid` is almost never used (and its one use can be easily refactored away), but it causes a lot of headache. In particular, `TextureManager2D::get` can fail, because of this invalid state.

In other words, I'd like to get rid of `GpuTexture2DHandle` and just use `GpuTexture` everywhere.

**Comment by Wumpf** [comment]
yeah I think we need to do some general work on the texture/mesh manager
I’m fairly happy with the texture/buffer pool by now, but the next layer above, that is “content hash based lookup + creation utilities + narrow ability via type” which is modled by those managers, didn’t turn out that well
A lof ot stuff in there was originally tuned for distinguishing “long lived” vs “short lived” to be able to use different allocators for those things. In practice this is only ever relevant for Buffers and doesn’t seem to be as worth while as originally assumed. So that’s a concept I want to cull for the time being

I guess it’s still useful to know via a type that a texture is two-dimensional, but then this would be just a straight wrapper of GpuTexture. In which case any GpuTexture can be converted to that doing a trivial runtime check
