### ISSUE TITLE
Using WASD+EQ with Ctrl Modifier results in program exit & save file. 

### ISSUE THREAD

**Issue by h3mosphere** [rerun-io/rerun#1867]
It seems that using the WASDEQ keys, for moving around the 3d view, the speed can be modified via Ctrl|Shift|Alt.  This is nice, however it appears to clash with application level keyboard shortcuts: Ctrl-Q, and Ctrl-S.

**To Reproduce**
1. Press Ctrl-Q or Ctrl-S, expecting fine movement in the Y-Up, or Z-Back direction.
2. The application quits, or pops up a save dialog.

**Expected behavior**
1. Maybe remove the application level key bindings. Needing to quit the application, and save, come up alot less frequently than fine-level control of camera, for certain data sets.
2. Have Shift + WASDEQ be the fine-level movement, instead of control. Perhaps even removing Control entirely. Currently Shift moves _very_ fast, for a dataset which is 70m+ in the X+Z directions, the dataset flies out of the view very easily.

**Your goals**
Move around the dataset to get a view from a particular point, needing quite fine level control over movement.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 22.10

**Comment by Wumpf** [comment]
Thanks for filing this!
(For all Mac users out there: You don't run into this problem because saving is via Cmd for you!)

imho neither removing the shortcuts nor removing the slow-down is great:
* application wide shortcuts at least for saving are so common, they are expected to work
* speed *plus* slowdown are useful to quickly support variety of scenes. But we may need to tweak the factors  & expose camera speed etc. as a user setting on the space views

With that stance the only way out is a different button for slowdown. Proposing to stick with Ctrl on Mac and use Alt on Windows & Linux. What do you think?

**Comment by h3mosphere** [comment]
Whichever seems most appropriate. Thinking about it now, it is probably best to stay away from CTRL as it is used most often with key combos that users will be familiar with.

Alt may already be bound to a speed 'mode'. I'll have a look at the the code see what the combinations are currently. 

Probably for someone else to weight in here on what is correct/blessed.

Thanks
