### ISSUE TITLE
Selected timeline heuristic is unstable

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#2186]
Try it yourself by running `examples/python/text_logging` a bunch of times: sometimes `log_time` wins, sometimes `frame_nr` wins, depending on the speed of ingestion.

**Comment by jleibs** [comment]
I've observed this leading to confusion on multiple occasions -- bumping priority to high so that it actually gets fixed.

Also marking as bug as this is a departure from our expected behavior of always defaulting to user-provided timeline.

The major challenge with implementing this is that there is a race-condition when we start laying out views where it's possible that the only data we have received is the `SetStoreInfo` message and thus have no timelines to base our decision off of.  Similar to other properties we probably need some form of an `EditableAutoValue` here.

**Comment by nikolausWest** [comment]
Solution: 
- make it an `EditableAutoValue`
- auto = first user timeline
