### ISSUE TITLE
rr.serve doesn't change port 

### ISSUE THREAD

**Issue by mix0z** [rerun-io/rerun#2514]
When you use rr.serve with custom ports the browser viewer continues listening to default port

**To Reproduce**
1. Use rr.serve with custom web_port and ws_port
2. Try to open in browser 
3. You will get re_viewer.js:1681 WebSocket connection to 'ws://adress:9877/' failed: 

**Screenshots**
![2023-06-26 12 43 06](https://github.com/rerun-io/rerun/assets/57793219/2ed283c8-a489-4af8-b8d6-276ac8a08057)
<img width="1018" alt="image" src="https://github.com/rerun-io/rerun/assets/57793219/1cc83da6-8039-4d2c-8266-319e59cc5f51">
![2023-06-26 12 46 16](https://github.com/rerun-io/rerun/assets/57793219/bdaaecea-daec-4f92-bda9-ca020fef9905)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 for serving and mac OS X for opening in browser
 

**Rerun version**
rerun_py 0.7.0 [rustc 1.69.0 (84c898d65 2023-04-16), LLVM 15.0.7] x86_64-unknown-linux-gnu prepare-0.7 9cf3033, built 2023-06-16T15:47:32Z

**Comment by emilk** [comment]
Thanks for the report! This is probably an easy fix - we'll try to get to it soon

**Comment by Wumpf** [comment]
@mix0z I have trouble reproducing that issue. I just tried with `rec.serve(True, 5002, 6002)` which correctly spawns a browser with http://localhost:5002?url=ws://localhost:6002

Did you maybe open http://localhost:5002 instead? That would then indeed to back to the default web socket port. Otherwise, can you try refreshing the browser and see if that helps?

**Comment by mix0z** [comment]
@Wumpf Yes, sorry, i just opened wrong address
