### ISSUE TITLE
Remove hover effect in checkboxes

### ISSUE THREAD

**Issue by martenbjork** [rerun-io/rerun#2727]
When hovered, the checkboxes grow in size. They shouldn't. The scale of the element should remain the same. Only the color should change on hover.

<img width="104" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/2ff7d92a-b40d-4651-8c40-d5615a614779">

**Comment by abey79** [comment]
Here is the current situation, which applies to all controls:
```rust
{
    // Expand hovered and active button frames:
    egui_style.visuals.widgets.hovered.expansion = 2.0;
    egui_style.visuals.widgets.active.expansion = 2.0;
    egui_style.visuals.widgets.open.expansion = 2.0;
}
```
Setting `hovered.expansion` to 0 removes the scaling on hover.

**Questions**:
- Should the scaling be removed on click as well (`active.expension = 0.0`? I would say this is not necessary as there is already some click feedback with thickening of the white check mark.
- How about `open.expension`? It refers buttons dropdown menu, see 2nd video.
- Since this is a rather global setting, do we expect undesirable side-effects (e.g. other types of widgets would _should_ scale on hover and/or activation)?

This is with both hovered and active set to 0.0:

https://github.com/rerun-io/rerun/assets/49431240/9ffef4a1-30c5-4801-a8e8-f2478e6e3ce9

Effect of `open.expansion = 2.0` (current situation):

https://github.com/rerun-io/rerun/assets/49431240/9ae1b454-c5ff-4da0-8d3b-d3b030da779f

**Comment by martenbjork** [comment]
I think scaling is a disorienting pattern. I think we should remove it across the app. Colors + hover cursor should be enough to signify interactivity. So, I think we should remove scaling from any interactive elements for now.

If we remove it, we will spot where states are missing and then we can fix that upstream in the design system 🙂

**Comment by abey79** [comment]
#2796 reverted by #2824
