### ISSUE TITLE
Use design system arrow icon across the app

### ISSUE THREAD

**Issue by martenbjork** [rerun-io/rerun#2738]
The design system contains an icon set with carefully designed arrows. Their size, ratio and pointiness are designed to be visually appealing.

<img width="297" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/3cab33c4-b6db-4b6c-9ff9-34960c691f53">

These elements currently use a different, much pointier arrow:

<img width="117" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/e11c64a8-fac5-43ea-b788-664247f15d0b">

<img width="129" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/1ca90a70-4d51-4220-9c2e-67571a0e62fb">

### TODO

Use the arrow icons as defined [in Figma](https://www.figma.com/file/3WX8yUqa8ECmhLwV6NIF3a/Rerun-Design-System?type=design&node-id=941-7408&mode=design&t=UEwrIbrfSM5Yz0sP-0) for all elements

- [x] large collapsing headers: #2920 
- [ ] ListItems
- [ ] Popup menus (related to https://github.com/rerun-io/rerun/issues/2734)
- [ ] ???

**Comment by abey79** [comment]
@martenbjork I'm experimenting with this. Because of the rotation animation, it's very advantageous to keep this thing a vector instead of a (raster) icon. I derived a linearised version of the path from a Figma-exported SVG:

<img width="442" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/563031f5-256e-4bcc-8745-2705b52f35e5">

<br/>
<br/>

This is it in action, at 250% UI zoom (top arrow only, the bottom two are the original ones):

<img width="641" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/9a10cf93-579b-478a-9a1b-6392edcdf887">

<br/>
<br/>

Can't say it's *not* visible, but it's certainly discreet with 100% UI zoom:

<img width="242" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/6f51a277-6e45-40d4-b8c0-c2d6e0659b39">

<br/>
<br/>

I'm inclined to keep that rounded version because it looks better at scale for a minimum costs (that's very few points), mainly because it makes me feel good :)  Any thoughts? How about the size of that triangle w.r.t. the text?
