### ISSUE TITLE
Colormap selection preview is sometimes bugged, sometimes not there at all

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#3242]
Here's a colormap selector for depth clouds -- no preview at all:
![image](https://github.com/rerun-io/rerun/assets/2910679/4f8a6c07-b742-4678-8373-24ecc3067d61)

And here's a colormap selector for tensors -- layout is broken:
![image](https://github.com/rerun-io/rerun/assets/2910679/cdc78012-5c39-419f-84be-85227b5dec08)

**Comment by emilk** [comment]
So there are two problems here:

A) we have two different code paths for selecting a colormap, and only one has the preview
B) the preview is broken

The broken preview is not because of egui, but because how we render it. I'm still investigating.

**Comment by emilk** [comment]
The `viewport` given to `new_renderer_callback` for each gradient image is correct:

![image](https://github.com/rerun-io/rerun/assets/1148717/ace8382e-da5d-4b78-9873-9fe2d4462c5d)

So the problem is either in
* how `egui_wgpu` handles the callback (maybe broke in https://github.com/emilk/egui/pull/3253)
* our `rectangle` shader (`re_renderer::renderer::TexturedRect`)
* our transforms (`re_renderer::view_builder::TargetConfiguration`)
