### ISSUE TITLE
Creating a space view is buggy

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#3462]
- You create the view
- The tab bar pretends that you're looking at the view
- But not really?
- You go to another view, comes back, and now it works

https://github.com/rerun-io/rerun/assets/2910679/9e2da783-51cd-430b-8802-62163b6f8af5

**Comment by emilk** [comment]
The bug here is that the newly created tab is not becoming active (front); it is only selected.

The UI is confusing here
* Bright white text = active
* Blue background = selected (i.e. shown in the selection view)

![image](https://github.com/rerun-io/rerun/assets/1148717/c51e1c6e-8135-4ba6-a7ad-676c6e32c0c9)
