### ISSUE TITLE
Make whether labels are shown a configurable property

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3465]
We currently have hard-coded threshold of 30 labels for whether to show labels.

These values should just govern a threshold, but whether we show labels our not should be configurable via the UI.

**Comment by Wumpf** [comment]
Related to
* https://github.com/rerun-io/rerun/issues/4266

**Comment by Wumpf** [comment]
Adding a bit of context since this comes up more and more often now:
The limit is in place for usecases where labels should show only on hover, most typically this is an issue with large point clouds where it wouldn't make sense to show all labels at once.

I propose to introduce a `hide labels` boolean component that internally has a visualizer-dependent fallback that accounts for this very issue. This may not be the final solution we want to arrive here (e.g. independent archetype is still on the table https://github.com/rerun-io/rerun/issues/4266), but it would be fairly easy to implement and solves the problem at hand that various users run into!

**Comment by jleibs** [comment]
This sounds great -- let's do it.

**Comment by emilk** [comment]
Maybe something for @kpreid
