### ISSUE TITLE
`MeshProperties` required to create mesh

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3473]
**Describe the annoyance**
Logging meshes now requires to create a `MeshProperties` object to set the vertex indices. This requires an extra import, and I need to remember what part of the mesh belongs into mesh properties and what not.

Feels like all the other arguments that `Mesh3D` takes are also mesh properties, so it feels a bit arbitrary that the indices are wrapped with a separate properties object.

Any reason for this split?

**Comment by nikolausWest** [comment]
Related: maybe we should have the rule of thumb that all objects that are expected arguments of an Archetype should go in the global namespace?

**Comment by teh-cmc** [comment]
> Feels like all the other arguments that Mesh3D takes are also mesh properties

The `Mesh3D` archetype doesn't contain _mesh_ properties but rather _vertex_ properties. The distinction is important because there is no relationship between the number of vertices vs. the number of indices, which would violate our instance count invariants if they were both present together at the top-level (whether we want to relax this invariant in the future remains to be determined).
https://github.com/rerun-io/rerun/blob/main/crates/re_types/definitions/rerun/archetypes/mesh3d.fbs#L29

**Comment by Wumpf** [comment]
But meanwhile we can crate an `__init__` method that takes `indices=` as a named argument. Seems like a good idea in any case, no?

**Comment by roym899** [comment]
Ah, that makes sense @teh-cmc, still a bit cumbersome to create, so I think having it as a direct argument would be nice to have.
