### ISSUE TITLE
`ImageEncoded` is missing `jpeg_quality`

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#3551]
Current:
```py
rr.Image(rr.TensorData(array=rgb, jpeg_quality=95))
```

Expected:
```py
rr.ImageEncoded(contents=rgb, jpeg_quality=95)
```

?

**Comment by Wumpf** [comment]
Don't think `ImageEncoded` should have a `jpeg_quality` know since that is an already encoded image and recompressing it would be odd imho. Also would require a lot more specification of what happens when jpeg bytes are passed in.

However, this is indeed missing from `rr.Image` itself!

**Comment by jleibs** [comment]
Conclusion from discussion is this *should* be an attribute of the ImageEncoded pseudarchetype rather than Image.

In this case "Image" = "We are transmitting non-encoded raw image data"
"ImageEncoded" = "We are sending encoded data blob which can be interpretted as an image"

"jpeg_quality" is a helper for *contructing* an encoded image.

This will be especially clear when ImageEncoded is its own archetype and we remove jpeg from the tensor data enum.

**Comment by Wumpf** [comment]
handing over to @jleibs who discussed this with @nikolausWest
everything done but without consideration of above comment on `andreas/python-missing-jpeg-quality`
