### ISSUE TITLE
Markdown heading levels all have the same font size

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3612]
See title. I'd expect smaller font size for higher heading levels.

**Additional context**
```
rerun_py 0.9.0-alpha.6 [rustc 1.72.1 (d5c2e9c34 2023-09-13), LLVM 16.0.5] x86_64-unknown-linux-gnu bde24df, built 2023-10-02T12:51:19Z
```

**Comment by haritha208** [comment]
assign the issue to me,currently i am working on ui & ux

**Comment by nikolausWest** [comment]
@haritha208: Do you know how to fix it? I believe it requires a fix in egui and/or egui_commonmark

**Comment by abey79** [comment]
repro:

```python
import rerun as rr

rr.init("md", spawn=True)

rr.log(
    "my_points",
    rr.TextDocument("""
# Heading level 1

## Heading level 2

### Heading level 3

#### Heading level 4

##### Heading level 5

###### Heading level 6

Body text
 """, media_type=rr.MediaType.MARKDOWN)
)
```

result:

<img width="997" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/1ca5035f-81d4-4be9-b414-13bb2a783db3">

I believe this might be due to some interaction between the way `egui_commonmark` sets up styling and our own `re_ui` customisations:
<img width="642" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/64fb120f-53d0-48bb-89fe-5cbd09f2f525">

**Comment by abey79** [comment]
Fixed by https://github.com/lampsitter/egui_commonmark/pull/20
