### ISSUE TITLE
Standardize how we show entity paths to the user

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#4338]
### Problem
Example entity paths, as currently shown with our `Display` implementation:

* `world/points`
* `images/"string"/segmentation`
* `images/"My Image.jpeg"/segmentation`
* `images/"Random text with newlines \n and quotes \"!"/segmentation`

As you see, newlines, quotes etc are already escaped in each individual string, so the formatted entity-path will not contain weird newlines etc.

Our `Debug` implementation for `EntityPath` is broken, and escapes newlines and backslashes _again_, which is just …bad, and should be fixed.

### String in paths
Note that there is a difference between _names_ (`world`, `points`, `images`, `segmentation`) and _strings_ (`"string", "My Image.jpeg", "Random text with newlines \n and quotes \"!"). Names are kind to struct-fields, while strings are kin to table keys. 

Maybe we shouldn't have this distinction, and instead do what most operating system do with paths: escape slashes and spaces (in addition to newlines etc) in embedded string, i.e.:  `images/My\ Image.jpeg/segmentation`.

### How to embed a path in a bigger string
So how do we show an entity path to the user when embedded in a larger string? In GUI:s we could use a separate background color or font, but that doesn't work everywhere (e.g. console logging), so I prefer a solution that is ASCII-based.

Using just `Display` seems like a bad idea:

* `eprintln!("There is a problem with {entity}")` -> `There is a problem with humanity`

Double-quotes will clash with existing quotes in the string:

* `eprintln!("There is a problem with \"{entity}\"")` -> `There is a problem with "certain/" bugs and "/issues"`

Single-quotes seems better:

* `eprintln!("There is a problem with '{entity}'")` -> `There is a problem with 'certain/" bugs and "/issues'`

### Enforcement
Let's assume for a second we opt to select all entity paths in single quotes - how do we enforce it?

We can change `Display` to add the  `'quotes'` around the entity-path, and then always use `Display` (i.e. `{}`) to display the strings. This is after all the purpose of `Display`. In the long-run we can add a lint against using Debug-formatting for anything user-facing, but in the short term we can change `Debug` to act exactly like `Display`. That way we can't go wrong, as long as we don't add extra explicit quotes (`\"{}\"), which we already have a lint against in `lint.py`.

There are cases though when entity-paths are standing alone in the UI (streams panel, selection panel) - do we really want to add single-quotes to those places too?

### Related issues
* https://github.com/rerun-io/rerun/issues/3697
* https://github.com/rerun-io/rerun/issues/3995

**Comment by abey79** [comment]
Some thoughts...

#### Context

I think there are two sub-cases to consider:
1) The entity is "embedded" in some text: `This component is part of $ENTITY`, or `This component is part of the $ENTITY entity` (btw, we should also standardise which of these two is preferred).
2) The entity is "stand-alone" somewhere where context makes clear that what is referred to is any entity, such as the selection panel title (when an entity is selected), or two-column property list: `Origin entity:     $ENTITY`.

Quoting feels useful for (1), but not so much for (2).

#### Navigation

Also, in most (all?) case, the entity should be clickable so that it can be selected. So one way to go about this would be to have a specific styling, e.g. underlined to mimic web link, or with some background shading. Always adding some entity icon there might help with consistency. We kind of do that already with space views (albeit using brighter text colour instead of underline):

<img width="160" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/b0d053fb-1f4a-4a72-90c9-b9559f5fcfae">

#### Shortening

Very often, the entity path can be become unwieldy. This can be especially bad with file names, etc. Allowing such a variation is not tractable in a consistent UI. We should probably roll a `/`-aware, centre-eliding shortning scheme (`/world/…/sensor`) that would be applied systematically, along with the full path in the tooltip.
