### ISSUE TITLE
Zooming in changes orbital camera origin

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#4402]
Currently when zooming in (beyond a certain point?) the origin of the orbital camera seems to change. I think this is not intuitive. I would never expect zoom in + zoom out result in a different origin position.

See video below (only zooming in and out after 0:15).

https://github.com/rerun-io/rerun/assets/9785832/adeae516-b95c-4049-9feb-2bfda6a535b8

Somewhat related to #965, but different issue.

**To Reproduce**
```
import rerun as rr
import numpy as np

rr.init("test", spawn=True)
rr.log("points", rr.Points3D(np.random.rand(10,3), radii=0.03))
```
Align origin with one of the points (like in the video), zoom far in, zoom out -> origin not at the same position anymore.

**Comment by Wumpf** [comment]
@emilk this is caused by the "move once too close" rule you added to the orbit camera. This ticket would essentially require dropping that again entirely. Not sure if that's what we want to do 🤔

**Comment by kpreid** [comment]
> … the "move once too close" rule you added to the orbit camera …

Oh, is this what's going on? I am very frequently inconvenienced by the orbit point not being anywhere near the place it ought to be, and now I understand that it's probably a combination of this and #4664.

**Comment by emilk** [comment]
The reason for the current behavior is that scrolling means "move closer", but for some users it can be confusing that you cannot get any closer after a while (because you are approaching the orbital center). So we added the feature that when you are very close to the orbital center, scroll moves it.

I can see how that is confusing though.

We could remove the "scroll to move" and replace it with some hint to the user, e.g. showing the orbital center as being very close when you scroll too close to it, perhaps with a suggestion to move it instead using WSAD
