### ISSUE TITLE
Add/remove entities modal doesnt allow adding to a 2D space view

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#4826]
The add/remove entities modal doesn't let adding anything to a 2D space view with he ARKit example. This is possibly a heuristics bug?

<img width="1225" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/5da5e329-499c-442a-88ef-a6ffcfca9a33">

### Repro

- Open ARKit example
- Remove everything from the blueprint
- Add an empty 2D space view
- Use the add/remove entities modal

Expected: stuff can be added (at least `camera_lowres` etc.)

Actual: nothing is enabled

**Comment by abey79** [comment]
The reason for this is that that 2D space view has a space origin that is not compatible with any 2D content. It's space origin should be set to the entity that has the pinhole transform (or below) to be able to accept content.

For 0.12, the workaround is to create a 2d space view with a suitable space origin from the `+` button in the blueprint panel.

In 0.13, it will be possible to change the space origin of a space view.

**Comment by Wumpf** [comment]
The behavior hasn't changed but:
* it is now possible to change the origin
* internally the situation is much better defined: None of the entities are visualizable from the space since they'd require a 3D->2D projection starting with a 2D eye which is an invalid transformation

So what's to do here now is to allow adding entities anyways (blueprint could do this!) and give the right hints why something doesn't execute a given visualizer.
