### ISSUE TITLE
`DepthMeter` is ignored

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#5070]
**Describe the bug**

The mesh no longer shows up.

**To Reproduce**
Go to: https://app.rerun.io/commit/b9cd458/?url=https://app.rerun.io/version/nightly/examples/arkit_scenes.rrd

**Expected behavior**
Should see the mesh

**Screenshots**
![image](https://github.com/rerun-io/rerun/assets/3312232/cfe5c977-74be-4b61-8f77-9e314ced7294)

**Backtrace**

**Desktop (please complete the following information):**
 - OS: Ubuntu.
 - Reproduces on both Native and Web

**Rerun version**

**Additional context**

**Comment by emilk** [comment]
Actually, the mesh is there. You just have to zoom in (on the labels) a lot:

![image](https://github.com/rerun-io/rerun/assets/1148717/49e3275d-b930-499c-a2de-8bb07353bf0d)

It is the depth point cloud that is extremely large

**Comment by emilk** [comment]
The problem sits in `SpaceViewBlueprint::on_frame_start`. It fills in a `per_system_entities` which is _empty_.

Why? Because every single entity has zero visualizers according to the `DataQueryResult` from `lookup_query_result`.

I suspect this got broken in https://github.com/rerun-io/rerun/pull/5050

**Comment by jleibs** [comment]
Confirmed, fixed by: https://github.com/rerun-io/rerun/pull/5068
