### ISSUE TITLE
Implement 3-state visibility control

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#5464]
Removing groups from the blueprint tree (https://github.com/rerun-io/rerun/pull/5326) resulted in a regression on visibility control. We decided to address it with a tri-state, inherited, visibility property ([huddle minutes](https://rerunio.slack.com/archives/C06MZT92U8J/p1710172794963309?thread_ts=1710165584.745789&cid=C06MZT92U8J)), whereby a given data result visibility is either unset (in which case it is inherited from parent), overridden to visible, or overridden to hidden. This means that the "eye" button needs to be tristate as well.

~~The initial proposal is to rotate over the 3 states with each click, and use 3 distinct icon, such as these:~~
<img width="244" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/9e808163-8456-41ac-834d-07e27a437571">

@jleibs's proposal below is a better shot, at least as initial implementation.

For the selection panel, the simplest change would be to change the check box to a 3-item combobox.

**Comment by jleibs** [comment]
There **is** a tri-state, but I still disagree that it needs a tri-state button + icon in the blueprint tree.

There is nearly zero value in the sequence:
 - Hide parent
 - Hide child of hidden parent

The intuitive UI pattern is to have toggle **always** toggle the state.
The challenge, when toggling is that in some cases there are two different ways to toggle the state. 

Specifically, this happens when a parent has a value, and a child has the opposite value.  When toggling the child we can either set the value explicitly, or we can clear it letting it take on the value of the parent.

My proposal is to **always** prefer clearing unless clearing the value would not achieve the intended toggle.  This means in most cases the toggle is a toggle between 2 states: cleared and opposite-of-parent.  Occasional sequencing may result in a parent and child having the same value, in which case toggle should still do the correct thing on first toggle, after which it can return to cleared on the second toggle.

In the selection panel, I think there is value to showing a proper and explicit tri-state, but this is a much different design context.
