### ISSUE TITLE
Embedded video doesn't work in doc-preview

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#5822]
For some reason in the doc previews, videos don't appear to work.

See: https://landing-8zs0bvf65-rerun.vercel.app/docs/getting-started/data-in/cpp

![image](https://github.com/rerun-io/rerun/assets/3312232/6f088023-8ef0-431f-a0db-7b24d21e9bd7)

**Comment by jprochazk** [comment]
Seems like the markdown parser we use doesn't parse HTML properly. It doesn't ignore the whitespace inbetween elements, or maybe it doesn't check the void element list before treating an element as one. In this case, the offending source code is:

```html
<video width="100%" autoplay loop muted controls>

<source src="https://static.rerun.io/c4c4ef1e4a1b25002da7c44d4316b0e07ae8d6ed_logging_data1_result.webm" type="video/webm" />
</video>
```

It seems to parse the `video` element as a void element, and the `source` + closing `video` tag are then ignored, because `source` does nothing on its own, and a closing tag in an invalid position is discarded.

**Comment by jprochazk** [comment]
Here's the workaround: https://github.com/rerun-io/rerun/pull/5826

Switching to a different markdown parser would be significantly more work right now
