### ISSUE TITLE
Support for adding Buttons + Backend Integration.

### ISSUE THREAD

**Issue by karanchahal** [rerun-io/rerun#5857]
I am unsure on how to add a button to a web based viewer. I realize that rerun is primarily based on rerunning pre recorded data so I am not sure what the tool's plan is for live data interaction.

Imagine a data recorder, I want to add a button that sends a message to the backend to start recording/stop recording.

Is this possible using the sdk ? If not, this would be very useful to build custom UI's on top of Rerun's stuff. This is a blocker on my usage of this tool for robotics visualization.

Thanks,
Karan

**Comment by Wumpf** [comment]
> I realize that rerun is primarily based on rerunning pre recorded data

That's actually not the idea, we even have demos that work with live camera feed :). But as you've already noticed things don't always play nicely with the webviewer.

You can't add buttons and callbacks to Rerun yet, but this has come up before here which is why I'm closing this as a duplicate (please re-open if this doesn't capture what you were after!)
* #2691

Today, you can only achieve this by adjusting the viewer from rust code and then building your own web-viewer which is a bit more complicated.

But given that you're using the web-viewer anyways, you could also consider adding additional controls yourself outside of the viewer onto the same html page and wire those up with whatever application provides the data that is received by the rerun web-viewer?
