### ISSUE TITLE
Should fall back to gl on native when vulkan fails

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#5968]
Linux environments, in particular inside of Docker frequently have issues with vulkan, but the gl backend works much more frequently.

Currently we get a cryptic crash:
![image](https://github.com/rerun-io/rerun/assets/3312232/73d2c036-4a42-40b9-a3d4-28188c054731)

Would be nice to instead fall back to gl.

**Comment by Wumpf** [comment]
Somewhat familiar with this crash. I fixed it for the upcoming wgpu version (can't be backported since there's an api breakage). That fix will allow us to react to this situation which boils down to "for unclear reasons any kind of surface creation fails". Would be nice to sit together and figure out where this comes from so we can fix it in wgpu - lots of people are hitting similar stuff.

**Comment by Wumpf** [comment]
I got a fix for this into wgpu by now  and it landed with 0.20. We have to upgrade our stack now and then retry

**Comment by Wumpf** [comment]
oh, it looks like we're only allowing GL when it's picked explicitly, I believed this was done automatically:
https://github.com/rerun-io/rerun/blob/main/crates/re_renderer/src/config.rs#L235

That would explain the previously described behavior perfectly well. We still should be able to handle the no-adapter-at-all case better though!
