### ISSUE TITLE
Blueprint file from 0.15.0 isn't compatible with new 0.16.0 version 

### ISSUE THREAD

**Issue by rgolovanov** [rerun-io/rerun#6403]
**Describe the bug**
Apparently the forward compatibility is broken between 0.15.0 -> 0.16.0 for blueprint files.

**To Reproduce**
1. Save blueprint in 0.15.0
2. Run viewer v0.16.0
3. Try to open saved blueprint

**Expected behavior**
No errors. Loading older blueprint files should work.

**Screenshots**
![image](https://github.com/rerun-io/rerun/assets/14174584/ef463b9f-7b2a-4290-8c97-ba95c9bc9be4)

**Desktop (please complete the following information):**
windows

**Rerun version**
0.16.0

**Comment by Wumpf** [comment]
Unfortunately, rrd (recording) and rbl (blueprint) files are generally not expected to be backwards compatible at this point, just as the warning notes.
For that we'll need to establish a conversion process from version to version and enforce this etc.. At this point we're lacking this mechanism and are still breaking the formats too often at a more fundamental level. Reaching backwards compatibility for our formats is naturally a thing we want to reach at some point but we haven't determined yet when we want to start this.

Going to close this ticket since we'll not fix the particular 0.15 -> 0.16 issue.

**Comment by rgolovanov** [comment]
@Wumpf , thanks for clarification. yes, sure but the problem is general and probably, this issue can be converted to more generic feature request?

**Comment by Wumpf** [comment]
👍  Done here now https://github.com/rerun-io/rerun/issues/6410
