### ISSUE TITLE
Rerun notebook widget eavesdrops on keyboard events while typing in another cell

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#6638]
To repro, run the cube example so that there is a viewer.

Edit a cell and start typing. For example, hit "space" and notice that the viewer pauses / resumes playback.

**Comment by emilk** [comment]
A quick-fix is to ignore certain events (like "space") when the egui viewport doesn't have focus (`ctx.input(|i| i.focused)`). Maybe a better fix is possible in egui… discussing in Slack.

**Comment by emilk** [comment]
From slack discussion: we should consider moving the `keydown` event handler from `document` to `canvas` here:

https://github.com/emilk/egui/blob/7bd0a4f7965ebade3c03403d0014bd7e60e67132/crates/eframe/src/web/events.rs#L70-L73

If we do we need to make sure that the canvas gets automatic focus (e.g. on egui.rs and rerui.io/viewer).

In general, any events that can be moved from `document` to `canvas` without loss of functionality should be moved in order to better support multiple eframe viewports in the same web view.

Some events, like `keyup`, should probably stay on `document` so that we don't miss a key release on e.g. (alt-)tab or similar.

For the events that are installed on `document`:
* check for focus in any document/window events before doing anything, especially `preventDefault/stopPropagation`

**Comment by jprochazk** [comment]
In order for the canvas element to be able to accept focus, it also needs to have a `tabIndex="0"` set. The `0` ensures that the canvas follows the focus order defined by the order in the document source.

**Comment by emilk** [comment]
We decided to do a quick-fix for this for now:

Ignore some key presses (space, arrow keys) in Rerun on web if mouse cursor isn't inside the viewer canvas. @jleibs is taking the lead on this.

**Comment by jleibs** [comment]
Playing around with this the proposed solution still feels quite awkward.

In particular, it becomes evident that keyboard shortcuts are broken in other ways. Events sent while the viewer is in focus still also get processed by the notebook. For example hitting "space" triggers a page-down.

**Comment by jleibs** [comment]
I realized this is in fact a regression, which is why nobody has complained. This is one of the things we were getting "for free" from the fact that the viewer was previously embedded in an iframe.

**Comment by jleibs** [comment]
Additional notes:
 - https://github.com/emilk/egui/pull/4718 addresses the main issue

There is a second regression which is that jupyter notebook (classic) sometimes responds to Rerun events. In particular, the "a" key when trying to navigate.

I believe this can be traced back to jupyter's keyboard manage itself being somewhat poorly behaved:
https://github.com/jupyter/nbclassic/blob/main/nbclassic/static/notebook/js/keyboardmanager.js#L175-L183

It might be possible for us to detect when we have focus and manually disable the jupyter keybooard manager: https://github.com/jupyter/notebook/blob/ca50f1af5afb525fd95b98b2e61e69db28094467/notebook/static/notebook/js/keyboardmanager.js#L234
 
This is not an issue in jupyterlab, which appears to follow better practices for event handling.
