### ISSUE TITLE
Default value for `Radius` component is too big

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#6723]
If you load the OPF example and change either the default or override `Radius`, it default to a Radius of `1.0` scene units, which makes the rendering crawl to a halt, effectively forcing the user to force-quite the viewer.

As a first step, we should change the default to instead be in UI points (e.g. 1.5 ui points). However, this just pushes the problem to when the user then changes units.

A proper solution is to use the old radius heuristics, which depend on the size of the scene, and the number of points in it (https://github.com/rerun-io/rerun/pull/6678#discussion_r1661047106)

**Comment by Wumpf** [comment]
Most of this is fixed on main already since we're using a different fallback by now.
However, the default _scene unit_ radius (when you change the little dropdown box on radius) is defaulting to 0.5 scene units which is not catastrophic on opf, but can be problematic. Let's mitigate this a bit by making it start with 0.1
