### ISSUE TITLE
DisconnectedSpace snippet is broken

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#6817]
To repro:
```
python docs/snippets/all/archetypes/disconnected_space.py 
```

This only creates a single space, but is expected to create two separate spaces.

Affects all versions from 0.13 -> 0.17

Last worked on 0.12

**Comment by Wumpf** [comment]
This happens because the core of our "heuristic engine" aggressively prunes out anything that might be internally redundant: https://github.com/rerun-io/rerun/blob/613a35bce11f76f66d47eb84d4a8ffc3ae922305/crates/viewer/re_viewport_blueprint/src/viewport_blueprint.rs#L379

Just removing this piece of code fixes the bug. The good news is that each View can do this internally where needed, using information like "disconnect" in the process well. But that also might create quite a bit of redundant handling 🤔. Behavior might also be slightly different since right now this is the last step. more annoyingly it's also the slowest and we'd really like to do that only if necessary.
I'm fairly sure we rely on this hierarchy based de-duplication mechanism for various scenarios, so just removing it is likely not an option.
