### ISSUE TITLE
Dataframe view: column visibility editor

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#7067]
- Add hook to `SpaceViewClass` to allow adding "stuff" to the view title bar
- Use it to display a list of check box for visibility control

Concept:
- Icon next to the component to hide the column

https://github.com/user-attachments/assets/5b3d976d-6787-44c6-9c3c-23ab8fba37f1

- To unhide (and also hide) use the btn in the title bar:
<img width="237" alt="Screenshot 2024-09-11 at 15 31 02" src="https://github.com/user-attachments/assets/428f07cc-7bf0-4eb6-96d2-b00efb6ac7fc">

**Comment by gavrelina** [comment]
Decision making update: 
**Separate UI for visibility of components from visibility of components.**
Implications for now:
- It is only possible to add/remove entity via entity path section. This means there is no implicit show/hide functionality for entity (unless all components are hidden from one entity).
- Visibility of components is only defined through show/hide UI. It is not the same as add/remove, neither it is connected or united with the entity path filter (so instead of having an option to ‘add/remove component AND hide/show component, to only use the latter for interacting with visibility in the UI. what exactly does it mean via DataOut-don't have an opinion there, but whatever it is - to only expose it as one action)
Pros:
- Reduces complexity
- Decoupling query from looks (if the show/hide is looks?)
- Smaller changes will allow to add value faster (instead of coupling it with entity path etc)
- Also valid for entities as rows in the future!
Cons:
- Does not help forming a mental model for our data model through UI (hierarchical relations between entities and components (soon archetypes))

How? 
**Icon in the header of the Viewer**
:white_check_mark: always visible!
:white_check_mark: no awkward interactions!
:x: a new interaction pattern for the viewer!!
:x: what if there are few tabs — might be weird if it appears/disappears

We'll embrace this weirdness in the context of an already seriously weird view and see how this feels/how users react :)
