### ISSUE TITLE
Warn on unsupported video

### ISSUE THREAD

**Issue by jprochazk** [rerun-io/rerun#7373]
When a user loads a video which we can't load for some reason (failed to load, unsupported container format, unsupported codec, etc.), we should report that to them in some way other than a short-lived warning notification.

Some error cases are:
- Firefox doesn't support `WebCodecs` outside of Nightly
- Safari doesn't support AV1
- Unsupported video container format
- Unsupported video codec (inside the container)
- Container parse error
- Codec configuration error
- Decode error (`WebCodecs`)

**Comment by gavrelina** [comment]
A ui/ux proposal! 
- highlight the component in the stream that causes an error to improve its discoverability
- in the error copy itself mention explicitly what's wrong and why and how users can recover from it (i.e. linking to github issue to follow or docs)
- visually display smth explicitly "broken" instead of the video in the Viewer, like this:

<img width="1301" alt="Screenshot 2024-09-09 at 16 00 25" src="https://github.com/user-attachments/assets/163aadfb-f72d-4ce0-855e-4dfec5b3facf">

**Comment by gavrelina** [comment]
@Wumpf makes a lot of sense! 

About the entity msg => it would also then be visible if users click on it via the blueprint, right? that would also largly increase the discoverability! I do worry (slightly) that copying it in few places comes across as "omg! so many errors everywhere, panic!", hence my initial idea was to only show at Blob level and highlight Blob in red so that users would go there to find it. so kinda direct them with color nudging :) what do you think? 

And moving forward from here it still makes sense to revise (revive?) the different gradations and make this thing work : https://github.com/rerun-io/rerun/issues/4304

**Comment by jprochazk** [comment]
From: https://github.com/rerun-io/rerun/pull/7398#discussion_r1753388072

> I don't know if you've experienced this scenario: You're playing a video on the web, and it suddenly fails with an error of some kind. The player just stops, and the controls become inactive, so you can't seek to a different point in the video anymore. But then you reload the page, and seek after the point where the player previously stopped with an error, and the video continues playing back just fine.
> 
> I think we could do a lot better than web video players here, by always allowing seek even in the case of an error, and more importantly also highlight which segments are broken on the timeline, so the user knows exactly where to seek next to try and catch a part of the video which _can_ be played back.
> 
> This kind of behavior would definitely follow our "handle anything the user throws at it" philosophy

**Comment by gavrelina** [comment]
@jprochazk I can already picture how we mark some specific events/part on the timeline where one encounters an "error"!
