### ISSUE TITLE
static=True image logging still stores all the data

### ISSUE THREAD

**Issue by nisseknudsen** [rerun-io/rerun#7404]
**Describe the bug**
I am using `rr.log(..., static=True)` with images and the expectation that the memory consumption should stay stable over time. I only want to see the latest logged image.
I also have the expectation that when opening the (web) viewer, I do not have to watch through all of the history to the current frame.
Both is not met for some reason.

**To Reproduce**
Script to repro (uses webcam `0` on macOS, but should work with any computer with we webcam. Maybe try `/dev/video0` for ubuntu).
[scratch_5.py.zip](https://github.com/user-attachments/files/16968845/scratch_5.py.zip)

**Expected behavior**
Sidebar data source size stays stable and whatever a single JPEG image takes, let's say 20mbyte to be generous.
Unfortunately, it doesn't

<img width="349" alt="image" src="https://github.com/user-attachments/assets/af24a8a9-0834-4b88-b333-6a6fb419280b">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.6.1

**Rerun version**
Tested on 18.0 and 18.2 with same unexpected outcomes.

**Additional context**
Discord post: https://discord.com/channels/1062300748202921994/1075873257124810852/1283124563902992537

**Comment by teh-cmc** [comment]
There are two issues at play:
1. Static chunks are not subject to the dangling detection/cleanup logic of the garbage collector, since static data as a whole is immune to garbage collection.
2. The decoded image cache doesn't subscribe to store events, and therefore continues caching stuff that has long been overwritten.

The fix for 1) is to properly account for static overwrites on the write path: patch all dangling references, decreases stats, fire events.
That should be a small amount of (likely tricky) code.

The fix for 2) is to set up a store subscriber so that the image cache drops overwritten data immediately.
That can range from trivial to extremely painful depending on how things are setup at the moment; I need to have a closer look.

**Comment by nisseknudsen** [comment]
Thank you for the fix! Can confirm it works now 🙏
