### ISSUE TITLE
Test monochrome AV1 video

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#7672]
And add it to our standard test videos

**Comment by Wumpf** [comment]
I speculated that the lack of monochrome & subsampling properties in the av1 codec string were the issue for firefox/safari. But this change does nothing to the support matrix:
https://github.com/rerun-io/re_mp4/compare/andreas/improve-av1-codec-string

(so not pushing that to main right now, since why change a running system 🤷 )
