### ISSUE TITLE
Break out examples utilities to make it easier to add new examples

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#789]
Break out utility functionality that we repeatedly use in our examples. At the very least we should break out utilities for downloading and caching datasets. These utilities should be part of the Python package and used by all examples. The goal is to make it easier to add new examples and make behaviour more consistent.

**Comment by Wumpf** [comment]
Unclear at this point what's missing: The SDKs come with key utilities by now for fast and easy setup from command line.

Asset asset was not done so far because the requirements are a bit too individual and having the samples run stand-alone is very important to us.

I think it's time to close this until we identify concrete missing things :)
