### ISSUE TITLE
`rerun <file>` does not work if there's already an open Rerun instance

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#7955]
In repository repro:

```
pixi run py-build
pixi run -e py python ./examples/python/dna/dna.py
pixi run rerun some_image_file_I_had_around.png
```
It says it streams to an existing viewer, but nothing ever shows.
On 0.19 the image opens in new rerun instance, also not what I expected to happen, but not as broken.

**Comment by teh-cmc** [comment]
I think I remember this working properly back when we merged https://github.com/rerun-io/rerun/pull/6951, hmm... :thinking: 

Lemme try this

**Comment by teh-cmc** [comment]
Yup, it sure is broken now. Digging.

**Comment by teh-cmc** [comment]
Welp, after a long dig into the git history, the only explanation I can come to is that I severely hallucinated when I merged this PR: the code cannot work because... well the code just isn't there. Literally, there is no code:
https://github.com/rerun-io/rerun/pull/6951/files#diff-2a04e2af4408b757cb5b308ac05290c50f5f04128f6d8072025f746849ebccf0R788-R790
```rust
} else if is_another_viewer_running {
    re_log::info!("Another viewer is already running, streaming data to it.");
    Ok(())
}
```
There's a print saying we're forwarding the data, but... we don't.

There's no such code anywhere in the history history so that doesn't look like a botched rebase..?! I have no idea what on earth is going on.

Well, whatever I guess, I'll just implement for forwarding logic.
