### ISSUE TITLE
Inconsistent drag-and-drop behavior: dropping multiple files results in multiple recordings

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#7965]
Start with the welcome screen. Drag and drop two images into Rerun.
* If you drag and drop them one at a time, they end up in the same recording (good!)
* If you drag and drop them both at the same time, you end up with two recordings (bad!)

**Comment by teh-cmc** [comment]
Haaa, and let me guess: if you drop two of them on top of an open recording, then it does work as expected?

The welcome screen has to recording-id to recommend, so that would make sense.

**Comment by teh-cmc** [comment]
Yep, confirmed that. Okay that should be a one liner then :eyes:

**Comment by teh-cmc** [comment]
The problem is trivial, and you'd hope the fix would be too... but then `SetStoreInfo` gets involved, and that's when you know all bets are off :melting_face:

I have something that's 99% there, but I'll need to finish another time as it gets mind-bendingly complex even though it has absolutely no right to...
