### ISSUE TITLE
`send_column` for encoded image does not assign an encoded image visualizer

### ISSUE THREAD

**Issue by oceanusxiv** [rerun-io/rerun#7980]
**Describe the annoyance**

**To Reproduce**
1. run, where encoded_images is a list of binary blobs
```py
rr.send_columns(
    "observation/wrist_image_left",
    times=[rr.TimeSequenceColumn("step", timesteps)],
    components=[
        rr.components.BlobBatch(data=encoded_images)
    ],
)
```
2. by default a spatial2Dview will not register a visualizer for this blob, even if I specify a `MediaType` column to specify the MIME type.

**Expected behavior**
Ideally if you pass the MIME type along, or really even if you didn't, the viewer should probably be able to guess a good visualizer for it, like other `send_column` types.

**Your goals**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.6

**Additional context**

**Comment by Wumpf** [comment]
What makes the visualizer show up automatically is the indicator component, not the media type. This is why the [example snippet for images](https://github.com/rerun-io/rerun/blob/main/docs/snippets/all/archetypes/image_send_columns.py#L20) first does a regular log first since that's the easiest way to get that in (this applies for _encoded_ images just like everything else).

This is a bit of an arcane corner of Rerun and not super well documented (it is mentioned on https://rerun.io/docs/concepts/visualizers-and-overrides#how-are-visualizations-produced but easy to miss). However, we want to remove those indicators and bake them into individual component tags, see
* https://github.com/rerun-io/rerun/issues/6889

**Comment by oceanusxiv** [comment]
Oh that's how you do it! Thanks for the tip.
