### ISSUE TITLE
Add File picker component to Blueprint

### ISSUE THREAD

**Issue by shivakanthsujit** [rerun-io/rerun#8215]
I have a blueprint that I use to view npz files that I log. I have a function to create the blueprint, one to load the npz file and one to log the data from the npz file to the blueprint. Currently I call the script with the path of the npz file I wish to view. I usually have folders of npz  files and would like to be able to quickly switch between them. Is there a way to have a component for entering a file path/drag and dropping a file and have it update the blueprint? Essentially there would be a callback on the file picker that calls my pipeline to load, and log to the blue print.

**Comment by teh-cmc** [comment]
It sounds like you're looking for an [external data-loader](https://rerun.io/docs/reference/data-loaders/overview#external-dataloaders)? See also this page about [sharing blueprints](https://rerun.io/docs/howto/visualization/reuse-blueprints), that'll probably come in handy.

I think this answers your question, feel free to re-open otherwise.
