### ISSUE TITLE
Compilation error on ubuntu20.04 aarch64

### ISSUE THREAD

**Issue by Yongtian8426** [rerun-io/rerun#8422]
**Describe the bug**
```
Consolidate compiler generated dependencies of target loguru
[  0%] Performing update step for 'arrow_cpp'
[  0%] Built target rerun_c_build
[  0%] Built target loguru
Consolidate compiler generated dependencies of target Catch2
[  0%] No patch step for 'arrow_cpp'
[  0%] Performing configure step for 'arrow_cpp'
CMake Error at /rerun/build/arrow/src/arrow_cpp-stamp/arrow_cpp-configure-.cmake:49 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '--preset' 'ninja-release-minimal' '-DARROW_BOOST_USE_SHARED=OFF' '-DARROW_BUILD_SHARED=OFF' '-DARROW_BUILD_STATIC=ON' '-DARROW_CXXFLAGS=' '-DARROW_COMPUTE=OFF' '-DARROW_IPC=ON' '-DARROW_JEMALLOC=OFF' '-DARROW_MIMALLOC=ON' '-DARROW_USE_ASAN=' '-DARROW_USE_TSAN=OFF' '-DARROW_USE_UBSAN=OFF' '-DBOOST_SOURCE=BUNDLED' '-DCMAKE_INSTALL_PREFIX=/rerun/build/arrow' '-DCMAKE_INSTALL_LIBDIR=lib' '-DCMAKE_INSTALL_BINDIR=bin' '-Dxsimd_SOURCE=BUNDLED' '-DBOOST_SOURCE=BUNDLED' '-DARROW_BOOST_USE_SHARED=OFF' '-DCMAKE_TOOLCHAIN_FILE=' '-GUnix Makefiles' '/rerun/build/arrow/src/arrow_cpp/cpp'

  See also

    /rerun/build/arrow/src/arrow_cpp-stamp/arrow_cpp-configure-*.log


make[2]: *** [rerun_cpp/CMakeFiles/arrow_cpp.dir/build.make:95: arrow/src/arrow_cpp-stamp/arrow_cpp-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:841: rerun_cpp/CMakeFiles/arrow_cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 17%] Built target Catch2
make: *** [Makefile:136: all] Error 2

```

**To Reproduce**
1. git clone git@github.com:rerun-io/rerun.git
2. git checkout 0.20.0
3. cmake -B build
4. cmake --build build -j

**Expected behavior**

**Screenshots**

**Backtrace**

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - aarch64

**Rerun version**
0.20.0

**Additional context**
Seems like sth related to arrow_cpp
```
root@20d5d0be2a28:/# rustc --version
rustc 1.79.0 (129f3b996 2024-06-10)

```

**Comment by Wumpf** [comment]
Generally we don't build the rerun repo raw from cmake, instead (specifically for c++ builds) we run `pixi run cpp-build-all`, see also our [build instructions](https://github.com/rerun-io/rerun/blob/main/BUILD.md) for details.

... but that said I was surprised to learn that it actually _does work_ on my Windows machine. So if you want to learn more about what's wrong you'll have to check the log it linked there (`/rerun/build/arrow/src/arrow_cpp-stamp/arrow_cpp-configure-*.log`). But more generally we don't support this path in the repository, only the commands in the pixi environment are supported. If you just want to use the SDK rather than building it from scratch, there's separate instructions here https://rerun.io/docs/getting-started/quick-start/cpp
