### ISSUE TITLE
World-space grid

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#872]
The 3D spatial view should have an option to show the X^Y, X^Z, and Y^Z planes as grids, as common in 3D apps.

**Comment by chengguizi** [comment]
Hi Rerun team, I am also interested in this feature. Showing a grid to tell the scale of the world is pretty useful feature!

**Comment by Wumpf** [comment]
There's three related we have to figure out for this:
* what should it look like (out of the box at least) and how does it behave under zoom
* what should be configurable
* how do we render it in a clean fashion

References:
* Unity [zoom](https://github.com/user-attachments/assets/72c2b1a5-2fe2-4ea5-91a1-b6c6aaf02ee5)
<img width="1237" alt="image" src="https://github.com/user-attachments/assets/eee5e725-9658-484e-bb83-bc54860a7126">
* Blender. [zoom](https://github.com/user-attachments/assets/8e497759-6bb6-4a66-92c2-6b7717d6ef80)
<img width="738" alt="image" src="https://github.com/user-attachments/assets/9e8a96f1-6a9b-44ad-b87b-2a1d03695bb4">
* Todo: more!

Both of these have a whole bunch of things in coming
* very thin, ui-constant sized lines (lines don't get smaller in the distance)
    * generally try not to get in the way!
* fading to cardinal lines
* fading in the distance

On cardinal lines: The problem mostly arises with zooming out. Fading lines is pretty much a must, otherwise the screen becomes gradually fully opaque no matter how small the lines are. So typically one would just fade everything but every tenth line (configurable?). That introduces a cardinality which likely should be expressed with a slightly different shader and/or thickness. Blender does this really well imho.

Another thing shown here is highlighting for cardinal axis. Blender has this configurable (for all axis independently!) but I'd keep this out for the moment, worth considering adding to the options.

Also seen in the blender clip is fading of the unlimited grid with distance which can be important to avoid artifacts as well. Unity actually just clips the lines off at some point. Which is also perfectly fine as long as the lines stay thin!

---

Unlike back in the day when this was first logged we now have a system in place for configuring views, and this is a great fit for that, so let's start by what the rough data modelling for this could look like:

```rust
table LineGuides3D {
    /// Whether the grid is visible.
    ///
    /// Default is true.
    visible: rerun.components.Visible ("attr.rerun.component_optional", nullable);

    /// The type of the grid.
    grid_type: rerun.blueprint.components.LineGuides3DType ("attr.rerun.component_optional", nullable);

    /// How the grid is oriented.
    orientation: rerun.blueprint.components.PlaneOrientation ("attr.rerun.component_optional", nullable);

    /// How thick the lines should be.
    ///
    /// Default is 0.5 ui unit. TODO: figure out exact value.
    // TODO: should we restrict this to small ui-based values? Scene values might be problematic.
    line_thickness: rerun.components.Radius ("attr.rerun.component_optional", nullable);

    /// Grid spacing of one line to the next.
    ///
    /// May differ per direction.
    ///
    /// Default is 1.0 in both directions.
    spacing: rerun.blueprint.components.GridSpacing ("attr.rerun.component_optional", nullable);

    /// Color of the grid lines.
    ///
    /// Default depends on background color
    // TODO: can we do inter-property in a sane way?
    color: rerun.components.Color ("attr.rerun.component_optional", nullable);

    /// Optional center of the grid, only relevant for non-infinite grids.
    center: rerun.components.Position3D ("attr.rerun.component_optional", nullable);

    /// Optional extent of the grid, only relevant for non-infinite grids.
    extent: rerun.components.HalfSize3D ("attr.rerun.component_optional", nullable);
}

enum LineGuides3DType: byte {
    /// A quasi-infinite grid is shown.
    Infinite (default),
    /// A finite grid anchored at a certain position.
    FinitePositioned,
}


enum PlaneOrientation: byte {
    /// A grid is shown in the XY plane.
    Xy (default),
    /// A grid is shown in the YZ plane.
    Yz,
    /// A grid is shown in the XZ plane.
    Xz,
}
```

---

Which brings us to the surprisingly hard topic of rendering:

There's Ben Golu's [pristine grid shader](https://bgolus.medium.com/the-best-darn-grid-shader-yet-727f9278b9d8) which is quality-wise perfect (also comes in versions for grid zooming and cardinal line highlighting) and can easily handle all fading out requirements. However, getting intersection with objects (we don't want a plane) can be tricky. And most importantly, all the complexity in it comes from the fact that it's not after constant pixel width lines, which all of the reference examples used:

> But there’s a catch. Most example grid shaders, like this one, use screen space width lines. That can be preferred over a texture based grid in a lot of use cases, and honestly probably what most people want. But it’s not what I’m trying to achieve. 

As long as we use thin constant-pixel-width-lines our line shader _should_ do the right thing. However, distance fade is still a concern for infinite grid that's hard to address since all lines converge to a solid (likely flickery) color. For sufficiently thin lines we don't have to fade them and can just stop half of them when we _know_ that they're getting too close together (this may be a shader or just some simple logic upon feeding the line renderer, note this is camera dependent).

Considerations for using a "shader on the plane" approach instead of a geometry (line renderer) based one
* much better filter/blending can be achieved easily (see linked blog post above)
* clean intersection / depth buffer interaction gets hard quickly!
    * possible workaround is to render the line-plane with alpha blending after the background (today background is rendered last). In order to facilitate _some_ degree of interaction with alpha blended objects that render later, depth buffer write stays enabled and pixels that are barely visible are discarded
* Potential quality & cpu side perf advantages need to be weighed against added complexity in render pipeline and perf costs on what amounts to almost a fullscreen pass (although technically drawn as a plane, it may fill the entire screen most of the time!)

Currently very much leaning towards just throwing a few hundred lines at our line renderer every frame and then see how it turns out. If this shows up in the profiler and/or is too hard to do nicely, we should add a new re_renderer `Renderer` and give it a special draw phase that puts it into the right place.

**Comment by Wumpf** [comment]
Found blender's grid shader
https://github.com/blender/blender/blob/main/source/blender/draw/engines/overlay/shaders/overlay_grid_frag.glsl
(careful! don't copy anything it's GPL licensed!)

The fact that there's so much going on in there to get the fading right makes me think more and more that using the general purpose line renderer is a dead end.
