### ISSUE TITLE
web: memory constantly grows then shrinks for seemingly no reason

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#909]
Look at the memory panel if both of these examples.

Native behaviour (`cargo r --release --features web -- examples/out/avocado.rrd`):

https://user-images.githubusercontent.com/2910679/214511965-dbfcc85c-e94c-4a1a-8966-617a5e448b3f.mp4

---

Web behaviour (`cargo r --release --features web -- --web-viewer examples/out/avocado.rrd`):

<screwed up the recording, gotta make a new one>

**Comment by emilk** [comment]
The saw-toothing is because of `wgpu`. Allocation callstacks:

```
wgpu_hal::gles::device::<impl wgpu_hal::Device<wgpu_hal::gles::Api> for wgpu_hal::gles::Device>::create_buffer::h95a01789c68e5abb@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[3369]:0x5d7a94
wgpu_core::device::queue::prepare_staging_buffer::hb09c3e769e7dec34@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[7421]:0x7fc196
wgpu_core::device::queue::<impl wgpu_core::hub::Global<G>>::queue_write_buffer::h94c9d15eacad360a@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[2038]:0x49a5df
<wgpu::backend::direct::Context as wgpu::context::Context>::queue_write_buffer::he1b7a577c3aebc91@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[4387]:0x6868dc
<T as wgpu::context::DynContext>::queue_write_buffer::hb05a919c3e92827c@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[12381]:0x94730a
wgpu::Queue::write_buffer::h8777518da1c6e23c@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[14917]:0x994cda
egui_wgpu::renderer::Renderer::update_buffers::he1504de8afe9981f@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[1100]:0x324ad5
<eframe::web::web_painter_wgpu::WebPainterWgpu as eframe::web::web_painter::WebPainter>::paint_and_update_textures::h411d5e2d6aababda@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[876]:0x29bd3d
eframe::web::backend::AppRunner::paint::h584aff3234354fd5@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[3351]:0x5d4423
eframe::web::events::paint_and_schedule::hb13fba93f89741be@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[1700]:0x42c80c
```

```
wgpu_hal::gles::device::<impl wgpu_hal::Device<wgpu_hal::gles::Api> for wgpu_hal::gles::Device>::create_buffer::h95a01789c68e5abb@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[3369]:0x5d7a94
wgpu_core::device::queue::prepare_staging_buffer::hb09c3e769e7dec34@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[7421]:0x7fc196
wgpu_core::device::queue::<impl wgpu_core::hub::Global<G>>::queue_write_buffer::h94c9d15eacad360a@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[2038]:0x49a5df
<wgpu::backend::direct::Context as wgpu::context::Context>::queue_write_buffer::he1b7a577c3aebc91@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[4387]:0x6868dc
<T as wgpu::context::DynContext>::queue_write_buffer::hb05a919c3e92827c@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[12381]:0x94730a
wgpu::Queue::write_buffer::h8777518da1c6e23c@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[14917]:0x994cda
egui_wgpu::renderer::Renderer::update_buffers::he1504de8afe9981f@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[1100]:0x324b6e
<eframe::web::web_painter_wgpu::WebPainterWgpu as eframe::web::web_painter::WebPainter>::paint_and_update_textures::h411d5e2d6aababda@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[876]:0x29bd3d
eframe::web::backend::AppRunner::paint::h584aff3234354fd5@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[3351]:0x5d4423
eframe::web::events::paint_and_schedule::hb13fba93f89741be@http://127.0.0.1:9090/re_viewer.js line 366 > WebAssembly.instantiate:wasm-function[1700]:0x42c80c
```

**Comment by emilk** [comment]
I try this:

```
cargo r -p raw_mesh -- --save ../lego.rrd
cargo r -p rerun --features web_viewer -- --web-viewer ../lego.rrd
```

And I see this:

![image](https://user-images.githubusercontent.com/1148717/225357295-bd8671b3-518b-430e-8eb0-daf759aa2b1e.png)

**Comment by Wumpf** [comment]
We have a decent picture of where these come from by now:

* the bug can't be reproduced with a native GL renderer since the allocations we're seeing are "buffer backing memory" of `wgpu::Buffers` which is only needed when mapping buffers is not possible
* it seems that the memory is exclusively from temp buffers on `wgpu::Queue` which are created on *every* write_buffer/write_texture call. This implies that any use of our `CpuWriteGpuReadBelt` is reducing the issue. However, we can't avoid it entirely right now since egui is still using the queue for uploading data every frame
* the rise in (average) memory usage over time is merely egui using more memory every frame since the memory graph has more and more lines over time. The easiest way to demonstrate this is by panning in the panel so that egui clips all lines, saying there for a while and then going back: Without the lines, the memory spikes stay lower.
* **we do not know why the temp buffers are freed in bursts**. Wgpu has no mechanism for delaying the buffer garbage collection. This directly originates from submission indices being thought of as in use or not in use
   * i.e. why does it go up and down if there is a constant stream of new frames?
   * it seems that the WebGL backend reports frames done (i.e. value on the signal handler) only every few frames
   * it should be possible to optimize the WebGL backend to discard the backing memory once it is known that a user won't use a buffer anymore (i.e. much earlier than when it is known that the gpu is no longer using a buffer)

Further investigation is needed, but with what we know the issue seems fairly contained, and not as worrisome as originally thought, especially if we continue to use the `CpuWriteGpuReadBelt` everywhere.
