### ISSUE TITLE
User configurable colormapping for all image types

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#910]
Today, we offer a bunch of color maps for the Tensor view and hardcode a color map (see #351) for depth images.
Instead, we want *all* images to be color mappable in a flexible fashion. The user should be able to pick from a range of different colormaps and provide their own.

Colormapping should be done from the raw data on-the-fly on the GPU. I.e. the color map data structure should be gpu friendly and be easy to be evaluated per-pixel on the fly.
(it could be that we want to do lossless conversion into a smaller set of known formats first before in order to get the number of permutations down the renderer code has to deal with).

**Comment by teh-cmc** [comment]
_I was dumping thoughts on the subject and realized there was already an issue for it! Allow me to add my notes._

## Apply color mapping and transfer functions on the GPU

We currently do color mapping by quite literally patching the image data in the image cache on the CPU.
We'd like to do this as a pixel shader instead.

- Well-known mapping functions (turbo, viridis, plasma...) can probably be implemented manually as wgsl modules and imported as needed.
- Custom transfer functions can likely be uploaded as some kind of range-lookup tables.

Note that this goes beyond images: raytraced & raymarched volumes are obvious use cases but even then, you should probably be able to colormap anything you want just by saying so and specifying either a well-known mapping function or a RLUT?

**Comment by teh-cmc** [comment]
_Quick messy notes following our looong discussion_

Sampling an albedo texture (whether it's a 2D one, or even a 3D one when rendering straight from 3D volumetric data!) really is just another kind of transfer function... kinda.
Sure at this point you're mapping some coordinates (2D or even 3D UVs) to a color rather than some kind of normalized value like you'd expect with a vanilla transfer function, but from a UX standpoint it's not that different.

So all in all, when trying to colormap something, you end up with:
- well-known colormaps
- custom transfer functions
- full on 2D or 3D textures

Now you can imagine that all of this is exposed as an `EntityProperty`, allowing the user to easily log the necessary data for colormapping via the SDK, and pick the right method through the selection panel:
```rust
enum ColorMap {
    Turbo,
    Viridis,
}

enum ColorMapper {
    /// Use a well-known color map, pre-implemented as a wgsl module.
    ColorMap(ColorMap),

    /// Use a custom, ranged look-up table as a transfer function.
    ///
    /// The entity path points to an entity that has a Tensor component representing the RLUT.
    ///
    /// The mapping itself is done in a wgsl shader to which we upload the custom RLUT.
    Transfer(EntityPath),

    /// Sample a 1D/2D/3D texture.
    ///
    /// The entity path points to an entity that has a Tensor component that can be interpreted as
    /// a 1D/2D/3D albedo texture.
    Texture(EntityPath),
}

struct EntityProperties {
    // [...]
    color_mapper: Option<ColorMapper>,
}
```

**Comment by nikolausWest** [comment]
Some things that should be included here:

- [ ] User configurable min-max range for color map
- [ ] Colormapping done on GPU

**Comment by teh-cmc** [comment]
A good chunk of this has been implemented already, the rest is in:
- #1612 
- #1588
